services:
  postgres:
    image: postgres:18-bookworm
    expose:
      - "5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql
  web:
    environment:
      DATABASE_URL: "postgresql://myuser:mypass@postgres:5432/mydb?schema=public"
    expose:
      - "3000"
    build:
      context: ./services/web
      dockerfile: Dockerfile.web.dev
    volumes:
      - ./services/web:/app
    depends_on: 
      - postgres
  nginx:
    image: nginx:1.28.1-alpine
    ports:
      - "8080:8080"
    volumes:
      # - ./infra/nginx/nginx.common.conf:/etc/nginx/conf.d/nginx.common.conf:ro
      # default.conf overrides the default config in nginx
      - ./infra/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

volumes:
  postgres_data: